# Generated by Django 2.1.4 on 2019-01-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akTeams', '0003_auto_20190122_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
