# Generated by Django 2.1.4 on 2019-01-30 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingEmployer', '0008_profile'),
        ('leaveRequests', '0002_auto_20190130_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_request_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('WAITING', 'waiting'), ('CANCELED', 'canceled')], max_length=50, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Employee', to='settingEmployer.Employee')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Manager', to='settingEmployer.Employee')),
            ],
        ),
    ]
