# Generated by Django 2.1.4 on 2019-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveRequests', '0003_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
