# Generated by Django 2.1.4 on 2019-01-31 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingEmployer', '0008_profile'),
        ('leaveRequests', '0005_auto_20190131_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_request_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('WAITING', 'waiting'), ('CANCELED', 'canceled')], max_length=50, null=True)),
                ('motif', models.CharField(blank=True, choices=[('Sick Day', 'accepted'), ('Unpaid', 'Unpaid'), ('Recovery', 'Recovery'), ('Vacation', 'Vacation'), ('Parental Leave', 'Parental Leave')], max_length=50, null=True)),
                ('reason', models.TextField(blank=True, max_length=200, null=True, unique=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Employee', to='settingEmployer.Employee')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Manager', to='settingEmployer.Employee')),
            ],
        ),
    ]
