# Generated by Django 2.1.4 on 2019-01-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveRequests', '0007_auto_20190131_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Employee', to='settingEmployer.Employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Manager', to='settingEmployer.Employee'),
        ),
    ]
