# Generated by Django 2.1.4 on 2019-01-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveRequests', '0008_auto_20190131_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
