# Generated by Django 2.1.4 on 2019-02-01 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveRequests', '0009_auto_20190131_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='motif',
            field=models.CharField(blank=True, choices=[('Sick Day', 'Sick Day'), ('Unpaid', 'Unpaid'), ('Recovery', 'Recovery'), ('Vacation', 'Vacation'), ('Parental Leave', 'Parental Leave')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
