# Generated by Django 2.1.5 on 2019-01-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_Code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cin_code', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cnss_code', models.CharField(max_length=30, unique=True)),
                ('experience_years_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_days_number', models.FloatField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('isManager', models.BooleanField(default=False)),
                ('be', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagmentItazouti.BusinessEntity')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagmentItazouti.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateTimeField()),
                ('expected_return_date', models.DateTimeField()),
                ('reason_leave', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Employee', to='leaveManagmentItazouti.Employee')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Manager', to='leaveManagmentItazouti.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveTypeCode', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('daysNumber', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagmentItazouti.LeaveRequest'),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagmentItazouti.LeaveType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='positon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagmentItazouti.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ManyToManyField(to='leaveManagmentItazouti.Team'),
        ),
    ]
