# Generated by Django 2.1.5 on 2019-01-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagmentItazouti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_request_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
