# Generated by Django 2.1.5 on 2019-01-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagmentItazouti', '0002_auto_20190129_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
