# Generated by Django 2.1.5 on 2019-01-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagmentItazouti', '0004_auto_20190129_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('WAITING', 'waiting'), ('CANCELED', 'canceled')], max_length=50, null=True),
        ),
    ]
