# Generated by Django 2.1.4 on 2019-01-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingEmployer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='be_Code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
