# Generated by Django 2.1.4 on 2019-01-30 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settingEmployer', '0002_businessunit_be_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cin_code', models.CharField(max_length=10, null=True, unique=True)),
                ('birth_date', models.DateField(null=True)),
                ('hire_date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('cnss_code', models.CharField(max_length=30, null=True, unique=True)),
                ('experience_years_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('leave_days_number', models.FloatField(blank=True, null=True)),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('tag_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='businessunit',
            old_name='label',
            new_name='libelle',
        ),
        migrations.AddField(
            model_name='employer',
            name='be',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settingEmployer.BusinessUnit'),
        ),
        migrations.AddField(
            model_name='employer',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingEmployer.Employer'),
        ),
        migrations.AddField(
            model_name='employer',
            name='positon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settingEmployer.Position'),
        ),
        migrations.AddField(
            model_name='employer',
            name='team',
            field=models.ManyToManyField(to='settingEmployer.Team'),
        ),
    ]
