# Generated by Django 2.1.4 on 2019-01-30 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settingEmployer', '0003_auto_20190130_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cin_code', models.CharField(max_length=10, null=True, unique=True)),
                ('birth_date', models.DateField(null=True)),
                ('hire_date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('cnss_code', models.CharField(max_length=30, null=True, unique=True)),
                ('experience_years_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('leave_days_number', models.FloatField(blank=True, null=True)),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('tag_manager', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('be', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settingEmployer.BusinessUnit')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingEmployer.Employee')),
                ('positon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settingEmployer.Position')),
                ('team', models.ManyToManyField(to='settingEmployer.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employer',
            name='be',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='positon',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='team',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
