# Generated by Django 2.1.4 on 2019-01-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingEmployer', '0005_auto_20190130_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='settingEmployer.Employee'),
        ),
    ]
