# Generated by Django 2.1.4 on 2019-01-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingEmployer', '0006_auto_20190130_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employer',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
