# Generated by Django 2.1.4 on 2019-01-22 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_Code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cin_code', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cnss_code', models.CharField(max_length=30, unique=True)),
                ('experience_years_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('be', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagementApp.BusinessEntity')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagementApp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('leave_date', models.DateTimeField()),
                ('expected_return_date', models.DateTimeField()),
                ('reason_leave', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_request_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('create_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Waiting', 'WAITING'), ('Rejected', 'REJECTED'), ('Accepted', 'ACCEPTED'), ('Canceled', 'CANCELED')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=400, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Employee', to='leaveManagementApp.Employee')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Manager', to='leaveManagementApp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveTypeCode', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagementApp.LeaveRequest'),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagementApp.LeaveType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagementApp.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='teams',
            field=models.ManyToManyField(to='leaveManagementApp.Team'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
