# Generated by Django 2.1.4 on 2019-01-10 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('leaveManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affectation_reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='leaveManagementApp.Employee'),
        ),
        migrations.AddField(
            model_name='memberteam',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='leaveManagementApp.Employee'),
        ),
        migrations.AddField(
            model_name='memberteam',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='leaveManagementApp.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='leaveManagementApp.MemberTeam', to='leaveManagementApp.Employee'),
        ),
    ]
