# Generated by Django 2.1.4 on 2019-01-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagementApp', '0002_auto_20190129_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='isVu',
            field=models.BooleanField(default=False),
        ),
    ]
