# Generated by Django 2.1.5 on 2019-02-04 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagementApp', '0003_auto_20190115_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cin_code', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cnss_code', models.CharField(max_length=30, unique=True)),
                ('experience_years_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('be', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagementApp.BusinessEntity')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagementApp.Employee')),
                ('positon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagementApp.Position')),
            ],
        ),
        migrations.RemoveField(
            model_name='employer',
            name='be',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='positon',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Employee', to='leaveManagementApp.Employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Manager', to='leaveManagementApp.Employee'),
        ),
        migrations.AlterField(
            model_name='memberteam',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveManagementApp.Employee'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='leaveManagementApp.MemberTeam', to='leaveManagementApp.Employee'),
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
