# Generated by Django 2.1.4 on 2019-01-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagementApp', '0003_leaverequest_isvu'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_days_number',
            field=models.FloatField(default=0),
        ),
    ]
